### ISSUE TITLE
Dependency not found with node 4.2.1 and npm 2.14.7

### ISSUE THREAD

**Issue by ismay** [davidtheclark/stylelint-selector-bem-pattern#11]
I'm using stylelint-selector-bem-pattern with a .stylelintrc and the stylelint CLI. When running my stylelint tests I get the following error:

```
> ismaywolff.nl@0.1.0 test:stylelint /Users/ismay/Projects/ismay.github.io
> stylelint '{src,lib}/**/*.css'

Error: Cannot find module 'postcss/lib/result'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ismay/Projects/ismay.github.io/node_modules/stylelint-selector-bem-pattern/index.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Code that resulted in this error can be found in this [branch](https://github.com/ismay/ismay.github.io/tree/lint-bem). 
  * [.stylelintrc](https://github.com/ismay/ismay.github.io/blob/lint-bem/.stylelintrc)
  * [package.json](https://github.com/ismay/ismay.github.io/blob/lint-bem/package.json)

When I install postcss manually with `npm i postcss` the error disappears, but that shouldn't be necessary right? Am I doing something wrong, or is this a bug?

**Comment by ismay** [comment]
The stylelintrc is just one of the versions I've tried btw. I've also tried:

```
{
  "extends": "stylelint-config-suitcss",
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "selector-bem-pattern": {
      "componentName": "[A-Z]+",
      "componentSelectors": {
        "initial": "^\\.{componentName}(?:-[a-z]+)?$",
        "combined": "^\\.combined-{componentName}-[a-z]+$"
      },
      "utilitySelectors": "^\\.util-[a-z]+$"
    }
  }
}
```

As described in your documentation, which resulted in the same error.

**Comment by davidtheclark** [comment]
Oh, looks like I forgot to add PostCSS to the dependency list, and nobody has noticed yet because they already had PostCSS installed for other reasons!

Boneheaded mistake, me!

That's a really easy fix. If you want to PR go ahead, otherwise I'll get it done probably tonight or tomorrow.

**Comment by ismay** [comment]
Ah cool. I don't think I'll have time tonight, running a little late already. But should you not have time tonight I can make a PR tomorrow. Thanks for the quick reply!

**Comment by ismay** [comment]
Ah it was a small fix anyway :)
