### ISSUE TITLE
Pass function instead of regex via .stylelintrc?

### ISSUE THREAD

**Issue by rgrjoh** [davidtheclark/stylelint-selector-bem-pattern#14]
Is it possible to pass a function instead of a regex string when configuring this plugin via a JSON-formatted `.stylelintrc`?

Eg. like this:

```
"rules": {
  "plugin/selector-bem-pattern": {
    "componentName": "[A-Z]+",
    "componentSelectors": {
      "initial": "function(componentName) {
        return new RegExp('^\\.' + componentName + '(?:-[a-z]+)?$');
      }",
      "combined": "function(componentName) {
        return new RegExp('^\\.combined-' + componentName + '-[a-z]+$');
      }"
    }
  }
}
```

**Comment by akella** [comment]
+1, came here for this question. Without possibility to pass a function we cant really customize codestyle conventions for original module :(. Like, at all.

**Comment by davidtheclark** [comment]
You can use the special string `{componentName}`, [as documented in the original module](https://github.com/postcss/postcss-bem-linter#componentselectors), to achieve what you're looking for.

**Comment by rgrjoh** [comment]
Yes it is possible and is what I’m doing now. The reason I’m asking about passing a function is that for more complex scenarios functions often make the construction of the regexp much easier for fellow developers (and your future self :-)) to understand since you can split it into variables that are reused.

**Comment by akella** [comment]
May be that would help you, i realized that might be restriction on stylelint side, because its just yaml-json file. So i just put a function that generates regexp (like these ones https://github.com/postcss/postcss-bem-linter/blob/master/lib/preset-patterns.js) in a comment in .stylelinrc. And just ran it on browser console to get actual regexp. Kinda workaround, but still.

**Comment by davidtheclark** [comment]
You can also write a `.stylelintrc.js` file as a CommonJS module that exports your configuration object (http://stylelint.io/user-guide/configuration/#loading-the-configuration-object). Give that a try!
