### ISSUE TITLE
componentSelectors.initial requires {componentName}

### ISSUE THREAD

**Issue by rgrjoh** [davidtheclark/stylelint-selector-bem-pattern#15]
When configuring stylelint-selector-bem-pattern via (a JSON formatted) .stylelintrc, I cannot get the initial selector to work unless it contains {componentName}. This is not the case when using postcss-bem-linter directly and configuring it via a function.

This may be an edge case, but a current use case of mine requires all selectors to be namespaced by a class selector:

```
.namespace .component-name {
}
```

With a config like this, all selectors are marked as errors:
```
"plugin/selector-bem-pattern": {
	"componentName": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
	"componentSelectors": {
		"initial": "^\\.namespace$",
		"combined": "^\\.namespace-{componentName}(?:__[a-z0-9]+(?:-[a-z0-9]+)*)?(?:--[a-z0-9]+(?:-[a-z0-9]+)*)?$"
	}
}
```

A workaround that seems to work is to add `({componentName})?` to the regex for initial:

```
"initial": "^\\.namespace({componentName})?$"
```

But that could allow incorrect selectors to sneak through. And, like I mentioned previously, it is not necessary when using postcss-bem-linter directly (i.e. not as a stylelint plugin).

Is this behaviour intentional, is it a bug, or am I missing something?

**Comment by davidtheclark** [comment]
On the one hand, I think that if you're not following a BEM pattern for this use-case then this plugin might not be for you.

However, it's possible that there's no good reason for what you're trying to be erroring out. If you want to try a PR to fix it, we'll see how that goes!

**Comment by rgrjoh** [comment]
Well, everything after that initial namespace selector follows a BEM pattern :-).

I had a look at the code to see if I could figure out what’s happening… and it looks like maybe it’s not in this plugin but in this file in postcss-bem-linter: https://github.com/postcss/postcss-bem-linter/blob/master/lib/to-interpolated-regexp.js It looks to me like a pattern that does not contain `{componentName}` would cause problems.

Changing line 6 in the above file to this seems to solve the problem:

```
return new RegExp(splitSource.length > 1 ? splitSource[0] + componentName + splitSource[1] : splitSource[0]);
```

I hope it’s ok to suggest a change like this. If you need a PR I’ll look into it but am short on time right now.

**Comment by davidtheclark** [comment]
@rgrjoh If you'd like to file a PR, go for it. Seems reasonable to me.

**Comment by simonsmith** [comment]
I would say this should be the job of the `namespace` in BEM/SUIT, not a separate selector.

**Comment by rgrjoh** [comment]
That sounds reasonable, but I don’t see how I can configure the linter to match the use case I described above.

**Comment by simonsmith** [comment]
Maybe the more BEM-like approach would be to refactor the CSS to:

```css
.namespace-component-name {
}
```

Or is that not possible?

**Comment by rgrjoh** [comment]
Ah, I misunderstood your comment. Yes, I agree, and that’s the rule used for the selectors following the first selector. Unfortunately getting rid of the first selector containing only the namespace isn’t possible in this case.

**Comment by davidtheclark** [comment]
Since this is an issue (and now a PR) with postcss-bem-linter, closing here.
