### ISSUE TITLE
Support Stylelint >=7.5.0

### ISSUE THREAD

**Issue by schoenwaldnils** [davidtheclark/stylelint-selector-bem-pattern#16]
Hi, I get following error-message:
```
Error: stylelint v7+ requires plugin rules to be namspaced, 
i.e. only 'plugin-namespace/plugin-rule-name' plugin rule names are supported. 
The plugin rule "selector-bem-pattern" does not do this, so will not work.
```
Are there plans to add support?

**Comment by davidtheclark** [comment]
@schoenwaldnils: This has already been addressed: https://github.com/davidtheclark/stylelint-selector-bem-pattern/pull/13/files, see https://github.com/davidtheclark/stylelint-selector-bem-pattern/blob/master/index.js#L6. Are you sure you're on the latest version of this plugin?

**Comment by schoenwaldnils** [comment]
Ah, sry. My bad :P
Now its working like charm.
