### ISSUE TITLE
It seems to default to suit, how can I set to BEM?

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [davidtheclark/stylelint-selector-bem-pattern#23]
Hi,

It seems to be working, but it is definitely not working in BEM methodology. The instructions took a long time to work out! There was no mention on the main page to add any comments to my CSS to make it work:

`/** @define mycomponent */` 

But i found it in another forum eventually.

This is my stylelintrc.js (pasted from the home page):

`module.exports = {
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "plugin/selector-bem-pattern": {
      "componentName": "[A-Z]+",
      "componentSelectors": {
        "initial": "^\\.{componentName}(?:-[a-z]+)?$",
        "combined": "^\\.combined-{componentName}-[a-z]+$"
      },
      "utilitySelectors": "^\\.util-[a-z]+$"
    },`

In my linted CSS file:

`.mycomponent-hello` is fine with it's '-', but:
`.mycomponent__hello` gives invalid component selector, and so does `.mycomponent--hello`

It does not like mycomponent either and wants it to start with capitals.

I am hoping I can get:

http://getbem.com/naming/

.block {}
.block__element {}
.block--modifier {}

Format without too much messing about :) Cheers!

**Comment by davidtheclark** [comment]
@Learn-Digital-Audio: As it says in this module's README, you'll need to read [the documentation for postcss-bem-linter](https://github.com/postcss/postcss-bem-linter) to learn about all the options available. There is a `bem` preset that should do what you're looking for.

If it doesn't work for you, you can file an issue or work out your own regular expression.

**Comment by Learn-Digital-Audio** [comment]
Thanks for your swift reply!

My main problem is my own ignorance of JS and JSON. I am changing career to web development and have decided to try to master different areas as I go in sequence. I am now finishing mastering CSS by learning BEM inside out... but I don't yet program JS.

Could you do me a massive favour and just tell me what to put in my .stylelintrc.js? I have read all the info on the page you linked and it seems to be in a totally different format. Here is what I need, how do I write that in my stylelintrc.js for stylelint-selector-bem-pattern?

https://github.com/postcss/postcss-bem-linter#defining-your-pattern

> 
> // use 'bem' conventions
> bemLinter('bem');
> bemLinter('bem', { namespace: 'ydx' });
> bemLinter({ present: 'bem', presetOptions: { namespace: 'ydx' }});

**Comment by davidtheclark** [comment]
The options you'll use for this rule in your stylelint config correspond to the options object you can pass as the argument to `bemLinter`. So what about this?

```json
"plugin/selector-bem-pattern": {
  "preset": "bem"
}
```

That should set you up with the `bem` preset.

**Comment by Learn-Digital-Audio** [comment]
Thanks for your help, I tried for ages and could not get it to do what I wanted. In the end I found this thread:

https://github.com/postcss/postcss-bem-linter/issues/82

And am going with adding this:

"selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",

May not quite as good, but basic protection against typos, and that was the main thing I was looking for :)

**Comment by a-tokyo** [comment]
I used the vanilla rule with a bit of custom config and it works perfectly:

```js
  rules: {
    /** selector class pattern must match [BEM CSS](https://en.bem.info/methodology/css) - [Regex](https://regexr.com/3apms) */
    'selector-class-pattern': [
      '^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$',
      {
        /** This option will resolve nested selectors with & interpolation. - https://stylelint.io/user-guide/rules/selector-class-pattern/#resolvenestedselectors-true--false-default-false */
        resolveNestedSelectors: true,
        /** Custom message */
        message: function expected(selectorValue) {
          return `Expected class selector "${selectorValue}" to match BEM CSS pattern https://en.bem.info/methodology/css. Selector validation tool: https://regexr.com/3apms`;
        },
      },
    ],
  },
```

**Comment by thewebartisan7** [comment]
> I used the vanilla rule with a bit of custom config and it works perfectly:
> 
> ```js
>   rules: {
>     /** selector class pattern must match [BEM CSS](https://en.bem.info/methodology/css) - [Regex](https://regexr.com/3apms) */
>     'selector-class-pattern': [
>       '^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-]?[a-z0-9]+)*)?$',
>       {
>         /** This option will resolve nested selectors with & interpolation. - https://stylelint.io/user-guide/rules/selector-class-pattern/#resolvenestedselectors-true--false-default-false */
>         resolveNestedSelectors: true,
>         /** Custom message */
>         message: function expected(selectorValue) {
>           return `Expected class selector "${selectorValue}" to match BEM CSS pattern https://en.bem.info/methodology/css. Selector validation tool: https://regexr.com/3apms`;
>         },
>       },
>     ],
>   },
> ```


Thanks works perfectly.
However for modifier value separated by single underscore "_" it seem to doesn't works.

Example:

```
block-name__element-name--modifier-name_modifier-value
```

**Comment by rich1e** [comment]
@thewebartisan7 Written like this, it seems useful

```regx
^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(--[a-z0-9]([-|_]?[a-z0-9]+)*)?$
```

**Comment by ptu14** [comment]
BEM allows to use class with key--value modificator:
e.g. `app-component--size--xl`

for that, you need modify regex: `^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)*(?:\[.+\])?$`

**Comment by meinenieuwland** [comment]
> BEM allows to use class with key--value modificator: e.g. `app-component--size--xl`
> 
> for that, you need modify regex: `^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)*(?:\[.+\])?$`

I think you should only be using 2 dashes to separate the class name and the modifier. Not inside the modifier itself. `app-component--size-xl`

**Comment by ptu14** [comment]
> > BEM allows to use class with key--value modificator: e.g. `app-component--size--xl`
> > for that, you need modify regex: `^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)*(?:\[.+\])?$`
> 
> I think you should only be using 2 dashes to separate the class name and the modifier. Not inside the modifier itself. `app-component--size-xl`

I think it's opinionated https://en.bem.info/methodology/quick-start/#key-value
