### ISSUE TITLE
Can't get implicitComponents option to work

### ISSUE THREAD

**Issue by ivangretsky** [davidtheclark/stylelint-selector-bem-pattern#24]
Good day!
Thank you for your work. Very useful plugin.

I need to make use of  `implicitComponents` option of postcss-bem-linter to[ automatically get definitions for components](https://github.com/postcss/postcss-bem-linter#define-components-and-utilities-implicitly-based-on-their-filename).

Here is my `.stylelintrc` contents, that should (as I thought) make it happen:
```
{
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "plugin/selector-bem-pattern": {
      "preset": "bem",
      "implicitComponents": "true"
    },
  }
```

But it does not work and produces this stylelint error: `Invalid option name "implicitComponents" for rule "plugin/selector-bem-pattern"`.

I am running stylelint as Atom plugin, if it matters.

Am I doing something wrong or is it a bug or some limitation?

**Comment by davidtheclark** [comment]
The options validation is done here: https://github.com/davidtheclark/stylelint-selector-bem-pattern/blob/master/index.js#L8. PR welcome to update the schema to include new options from postcss-bem-linter.

**Comment by ivangretsky** [comment]
That is the way to make more people get involved in the open source)
I did try to modify this part of code with no luck (it was ` implicitComponents: [true]`).
As it is my 1st line of non-jQuery javascript I can't be sure I will come up with a PR any time soon. But will make attempts.

**Comment by davidtheclark** [comment]
`true` should be replaced with a function that checks if the value is a boolean. It could also be `false`, right?

If the error went away but the plugin did not work I don't know what to say. Are you using the latest versions of each module? Did you try debugging to make sure this module is passing the correct options to postcss-bem-linter? Are you sure the option works if you use postcss-bem-linter on its own?

**Comment by ivangretsky** [comment]
Actually `true` should be replaced with a `true` or `false` or glob (or something like that).

I did manage to set up `postcss-bem-linter` with `gulp-postcss`. I spotted [another issue](https://github.com/postcss/postcss-bem-linter/issues/109), but it does not explain the current `stylelint-selector-bem-pattern` behavior anyway. With added option

```
var optionsSchema = {
  ...
  implicitComponents: ['true'],
  ...
};
```
I get no error even in the situation it has to be present.

**Comment by davidtheclark** [comment]
> a true or false or glob

??? No, it needs to be a function that returns `true` if the value is a boolean, `false`, otherwise.

> I actually do not know how to do it yet.

Hopefully the `postcss-bem-linter` docs can guide you through this.
