### ISSUE TITLE
Presets option not working? Constantly get error.

### ISSUE THREAD

**Issue by KingScooty** [davidtheclark/stylelint-selector-bem-pattern#4]
I've set up `stylelint-selector-bem-pattern` as the docs require. I'm using the right version numbers for everything, but i can't seem to get it working with the `bem` preset?

This is my config:

```javascript
  var stylelintConfig = {
    "plugins": [
      "stylelint-selector-bem-pattern"
    ],
    "rules": {
      "block-no-empty": true,
      "color-no-invalid-hex": true,

      "selector-bem-pattern": [2, {
        "preset": 'bem'
      }]
    }
  };

  var processors = [
    stylelint(stylelintConfig),
    reporter({
      clearMessages: true,
    })
  ];

  return gulp.src(
      ['app/assets/_scss/**/*.scss', '!app/assets/_scss/vendor/**/*.scss']
    )
    .pipe(postcss(processors, {syntax: syntax_scss}));
```

I've added the correct comment at the top of the css files: e.g `/** @define gs-o-media-island */`

But all i ever get back is the following:

```sh
[16:46:03] Starting 'sass-lint'...
[16:46:04] 'sass-lint' errored after 445 ms
[16:46:04] Error in plugin 'gulp-postcss'
Message:
    You tried to `@define` a component but have not provided a `componentSelectors` pattern
```

I've tried setting the `componentSelectors` option, but i still get the same error as above.

**Comment by jeddy3** [comment]
Oops, it looks like the example in the readme wasn't correctly updated to reflect the new config syntax introduced in stylelint `3.0.0`.

Try stripping out the number serverity from your config. e.g.:

```js
var stylelintConfig = {
    "plugins": [
      "stylelint-selector-bem-pattern"
    ],
    "rules": {
      "block-no-empty": true,
      "color-no-invalid-hex": true,

      "selector-bem-pattern": { "preset": "bem" }
    }
  };
```

I know this works as we're [using the plugin](https://github.com/stylelint/stylelint.github.io/blob/master/package.json#L29) for linting the CSS of the stylelint website.

I've created a [PR](https://github.com/davidtheclark/stylelint-selector-bem-pattern/pull/5) to correct the example in the README:

**Comment by KingScooty** [comment]
@jeddy3 Cheers! That does the trick! :+1:  Thanks for the quick response! :)
