### ISSUE TITLE
unknown escape sequence (Documentation error?)

### ISSUE THREAD

**Issue by VinSpee** [davidtheclark/stylelint-selector-bem-pattern#7]
When providing a regex for the utility selector property as the docs state, I get a 

```
YAMLException: unknown escape sequence in "/Users/vincespeelman/Projects/space/.stylelintrc" at line 11, column 32:
            "utilitySelectors": "^\.blank-u-(?:(?:bb|sm|md|lg|gg)-)
```
error. I noticed all of the other docs are double-escaping the regex, I assume the utility selector needs to be as well?

**Comment by davidtheclark** [comment]
Yes, this is a typo in the docs.
